name: Rust

on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./nextion_flash

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release && strip target/release/nextion_flash && mv target/release/nextion_flash target/release/nextion_flash_amd64

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            nextion_flash/target/release/nextion_flash_amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-win:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: ./nextion_flash

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: nextion_flash/target/release/nextion_flash.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mac:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: ./nextion_flash

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: Build for mac
        run: cargo build --all --release && strip target/release/nextion_flash && mv target/release/nextion_flash target/release/nextion_flash_darwin

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            nextion_flash/target/release/nextion_flash_darwin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
